# Generated by Django 4.2.2 on 2023-07-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_alter_advertisements_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisements',
            table='advertisements',
        ),
    ]
