# Generated by Django 4.2.2 on 2023-07-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0003_alter_advertisements_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='test_column',
            field=models.CharField(default='', max_length=100, verbose_name='test'),
        ),
    ]
